import * as THREE from 'three';
import { gsap } from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
gsap.registerPlugin(ScrollTrigger);

const canvas=document.querySelector('#cinema'), reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const dialog=document.querySelector('#how-dialog');document.querySelector('#how').onclick=()=>dialog.showModal();dialog.querySelector('.close').onclick=()=>dialog.close();
try { run(); } catch (error) { canvas.style.display='none'; console.warn('Cinematic fallback enabled',error); }
function run(){
 const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,innerWidth<720?1.25:1.75));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
 const scene=new THREE.Scene();scene.background=new THREE.Color('#0b0c0d');scene.fog=new THREE.Fog('#0b0c0d',11,34);
 const camera=new THREE.PerspectiveCamera(35,innerWidth/innerHeight,.1,100);camera.position.set(0,1.1,7);
 const key=new THREE.SpotLight('#f0ece4',160,30,.58,.7,1);key.position.set(4,7,5);key.castShadow=true;key.shadow.mapSize.set(1024,1024);scene.add(key,new THREE.HemisphereLight('#64777b','#08090a',1.4));const rim=new THREE.PointLight('#d5d0c7',26,13);rim.position.set(-4,2,-4);scene.add(rim);
 const floor=new THREE.Mesh(new THREE.PlaneGeometry(60,60),new THREE.MeshStandardMaterial({color:'#111214',roughness:.84,metalness:.03}));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;floor.position.y=-1.65;scene.add(floor);
 const root=new THREE.Group();scene.add(root); const vial=vialModel(), shipper=shipperModel(vial.clone()), truck=truckModel(), india=new THREE.Group();root.add(vial,shipper,truck,india);
 shipper.visible=false;truck.visible=false;india.visible=false;
 function phase(n){vial.visible=n<2;shipper.visible=n>=1&&n<3;truck.visible=n>=3&&n<5;india.visible=n>=5; if(n===4){key.color.set('#d0b4aa');rim.color.set('#8f605a')}else{key.color.set('#f0ece4');rim.color.set('#d5d0c7')} document.querySelector('#thermal-readout').textContent=n>=4?'8.7°C':'4.2°C';}
 phase(0);
 const sections=[...document.querySelectorAll('.scene')]; sections.forEach((section,i)=>{ScrollTrigger.create({trigger:section,start:'top center',end:'bottom center',onEnter:()=>phase(i),onEnterBack:()=>phase(i)});const copy=section.querySelector('.copy');if(copy&&!reduced)gsap.fromTo(copy,{autoAlpha:.35,y:28},{autoAlpha:1,y:0,duration:.8,ease:'power2.out',scrollTrigger:{trigger:section,start:'top 72%',toggleActions:'play none none reverse'}})});
 const choreography=gsap.timeline({scrollTrigger:{trigger:'#story',start:'top top',end:'bottom bottom',scrub:reduced?false:1.25}});
 choreography.to(camera.position,{x:1.1,y:.8,z:4.1,duration:1}).to(vial.rotation,{y:.65,duration:1},0).to(camera.position,{x:-.4,y:1.8,z:7.7,duration:1}).to(shipper.rotation,{y:-.28,duration:1},1).to(camera.position,{x:3.3,y:1.3,z:10,duration:1}).to(truck.position,{x:-.6,duration:1},2).to(camera.position,{x:0,y:7,z:15,duration:2}).to(india.rotation,{x:-.25,y:.08,duration:2},4);
 if(!reduced){gsap.to(root.rotation,{y:.12,duration:1.4,yoyo:true,repeat:-1,ease:'sine.inOut'});gsap.to('#thermal-readout',{opacity:.62,duration:1.4,yoyo:true,repeat:-1,ease:'sine.inOut'});gsap.to('.route-card',{borderColor:'#6f7f6d',duration:2,yoyo:true,repeat:-1,ease:'sine.inOut'})}
 buildIndia(india);
 let active=true;document.addEventListener('visibilitychange',()=>active=!document.hidden);let raf;function render(){raf=requestAnimationFrame(render);if(!active)return;camera.lookAt(0,.1,0);renderer.render(scene,camera)}render();
 addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setPixelRatio(Math.min(devicePixelRatio,innerWidth<720?1.25:1.75));renderer.setSize(innerWidth,innerHeight)});
}
function material(color,rough=.5,metal=0){return new THREE.MeshPhysicalMaterial({color,roughness:rough,metalness:metal,clearcoat:metal?.3:0,clearcoatRoughness:.25})}
function vialModel(){const g=new THREE.Group(),glass=new THREE.MeshPhysicalMaterial({color:'#d9e1db',roughness:.08,metalness:0,transmission:.55,transparent:true,opacity:.83,thickness:.2});const body=new THREE.Mesh(new THREE.CylinderGeometry(.52,.56,1.45,48),glass);body.position.y=-.25;body.castShadow=true;const liquid=new THREE.Mesh(new THREE.CylinderGeometry(.47,.5,.63,40),new THREE.MeshPhysicalMaterial({color:'#d1d9c7',roughness:.28,transmission:.15,transparent:true,opacity:.7}));liquid.position.y=-.58;const neck=new THREE.Mesh(new THREE.CylinderGeometry(.26,.29,.35,32),glass);neck.position.y=.65;const cap=new THREE.Mesh(new THREE.CylinderGeometry(.34,.34,.17,32),material('#b7b8b5',.25,.85));cap.position.y=.91;const stopper=new THREE.Mesh(new THREE.CylinderGeometry(.23,.23,.12,32),material('#303233',.6));stopper.position.y=1.01;const label=new THREE.Mesh(new THREE.CylinderGeometry(.565,.565,.5,48,1,true),new THREE.MeshStandardMaterial({color:'#e7e2d7',roughness:.75}));label.position.y=-.18;const line=new THREE.Mesh(new THREE.BoxGeometry(.005,.015,.52),material('#17191b'));line.position.set(.567,-.18,0);g.add(body,liquid,neck,cap,stopper,label,line);g.scale.setScalar(1.25);return g}
function shipperModel(vial){const g=new THREE.Group();vial.position.set(0,.05,0);vial.scale.setScalar(.75);const box=new THREE.Mesh(new THREE.BoxGeometry(3.6,2.3,2.7,4,2,4),material('#c8c4bb',.82));box.castShadow=true;box.receiveShadow=true;const foam=new THREE.Mesh(new THREE.BoxGeometry(2.9,1.65,2.05),material('#e7e4dc',.94));foam.position.y=.05;const seam=new THREE.Mesh(new THREE.BoxGeometry(3.66,.035,2.73),material('#6d6b66',.8));seam.position.y=.95;const mark=new THREE.Mesh(new THREE.PlaneGeometry(1.45,.42),new THREE.MeshStandardMaterial({color:'#252627',roughness:.8}));mark.position.set(0,.2,1.36);g.add(box,foam,seam,mark,vial);g.position.set(0,-.45,0);return g}
function truckModel(){const g=new THREE.Group(),white=material('#c8c9c6',.4,.15),dark=material('#252729',.55,.45);const cargo=new THREE.Mesh(new THREE.BoxGeometry(5.3,2.55,2.25,5,2,3),white);cargo.position.set(.55,.2,0);cargo.castShadow=true;const cab=new THREE.Mesh(new THREE.BoxGeometry(1.55,1.95,2.15,4,2,3),material('#747878',.38,.5));cab.position.set(-2.75,-.08,0);cab.castShadow=true;g.add(cargo,cab);for(const x of[-2.75,1.75])for(const z of[-1.08,1.08]){const tyre=new THREE.Mesh(new THREE.CylinderGeometry(.52,.52,.35,24),material('#121314',.75));tyre.rotation.x=Math.PI/2;tyre.position.set(x,-1.03,z);tyre.castShadow=true;g.add(tyre)}const stripe=new THREE.Mesh(new THREE.PlaneGeometry(4.6,.18),material('#6f7f6d',.55));stripe.position.set(.8,.12,1.14);g.add(stripe);g.scale.setScalar(.72);g.position.set(0,-.55,0);return g}
async function buildIndia(g){const routePts=[[-.45,-.7],[-.33,-.5],[-.15,-.25],[-.04,.02],[.2,.3],[.02,.78]];const route=new THREE.Line(new THREE.BufferGeometry().setFromPoints(routePts.map(([x,y])=>new THREE.Vector3(x,y,0))),new THREE.LineDashedMaterial({color:'#d5d0c7',dashSize:.06,gapSize:.04}));route.computeLineDistances();route.scale.setScalar(4.7);g.add(route);for(const [x,y] of routePts){const p=new THREE.Mesh(new THREE.SphereGeometry(.045,12,12),material('#f0ece4',.3,.2));p.position.set(x*4.7,y*4.7,.05);g.add(p)}try{const data=await fetch('/india_boundaries.geojson').then(r=>r.json());const positions=[];data.features.forEach(f=>{const polys=f.geometry.type==='MultiPolygon'?f.geometry.coordinates:[f.geometry.coordinates];polys.forEach(poly=>poly.forEach(ring=>ring.forEach(([lon,lat])=>positions.push((lon-79)*.12,(lat-22)*.12,.01))));});if(positions.length){const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));g.add(new THREE.Points(geometry,new THREE.PointsMaterial({color:'#9e9b95',size:.012,sizeAttenuation:true,transparent:true,opacity:.52})))}}catch(e){console.warn('India geometry unavailable',e)}g.position.y=-.55;g.scale.setScalar(1.05)}
